In [12]:
# Copyright (c) 2016, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# check python version; warn if not Python3
import sys
import warnings
if sys.version_info < (3,0):
    warnings.warn("Optimized for Python3. Performance may suffer under Python2.", Warning)

import gym

from Config import Config
from Server import Server

# Parse arguments
for i in range(1, len(sys.argv)):
    # Config arguments should be in format of Config=Value
    # For setting booleans to False use Config=
    x, y = sys.argv[i].split('=')
    setattr(Config, x, type(getattr(Config, x))(y))

# Adjust configs for Play mode
if Config.PLAY_MODE:
    Config.AGENTS = 1
    Config.PREDICTORS = 1
    Config.TRAINERS = 1
    Config.DYNAMIC_SETTINGS = False

    Config.LOAD_CHECKPOINT = True
    Config.TRAIN_MODELS = False
    Config.SAVE_MODELS = False

gym.undo_logger_setup()

# Start main program
Server().main()

ValueError: not enough values to unpack (expected 2, got 1)

In [7]:
def loglikelihood(actions, means, log_stds):
    return np.sum( 1.0/np.sqrt(2 * np.pi)/np.exp(log_stds) * np.exp( -1.0/2/(np.exp(log_stds)**2) * (actions - means) ** 2) )

In [6]:
import numpy as np
np.pi

3.141592653589793

In [11]:
means = np.array([0,3])
log_stds = np.array([1,3])
actions = np.array([2,4])
loglikelihood(actions, means, log_stds)

0.13179807060535279

In [79]:
import tensorflow as tf
p = np.array([[2,2],[3,4]])
q = np.array([[3,6],[5,2]])
x1 = tf.placeholder(tf.float32,[None,2])
w = tf.Variable(tf.truncated_normal([2,2]))
b = tf.constant(np.pi)
x2 = tf.placeholder(tf.float32,[None,2])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result1 = tf.log(x1/x2)
    result2 = tf.square(tf.add(result1,x2))
    result4 = tf.log(np.pi)
    #result 
    print (sess.run(result4))
    print (sess.run(result1,feed_dict = {x1:p,x2:q}))
    result3 = tf.reduce_sum(result2)
    print(sess.run(result2,feed_dict = {x1:p,x2:q}))
    print(sess.run(result3,feed_dict = {x1:p,x2:q}))
    
    ds = tf.contrib.distributions
    tf.contrib.distributions.kl(distribution_1, distribution_2)
    p = ds.Normal(loc=0., scale=1.)
    q = ds.Normal(loc=1., scale=2.)
    kl = ds.kl_divergence(p, q)
    print(kl)

1.14473
[[-0.4054651  -1.09861231]
 [-0.51082557  0.69314718]]
[[  6.73161125  24.02360153]
 [ 20.15268707   7.25304174]]
58.1609


TypeError: __init__() got an unexpected keyword argument 'loc'

In [47]:
result = np.array([[7.9078054,12.11455059],
 [  8.32915878 ,5.34895802]])

In [48]:
np.mean(result)

8.4251181974999998

In [53]:
np.log(4)

1.3862943611198906

In [66]:
np.log(p/q)

array([[-0.40546511, -1.09861229],
       [-0.51082562,  0.69314718]])

In [78]:
with open('qwe.txt','a+') as f:
    f.write('oiuou7')

In [80]:
22917/60/60

6.365833333333333

In [81]:
def p(x):
    return 1.0/x/x

In [84]:
p.all

AttributeError: 'function' object has no attribute 'all'

In [85]:
def kl(old_mean,new_mean,old_std,new_std):
    term1 = np.log(old_std/new_std)
    term2 = 0.5*(1-(old_std/new_std)**2-((old_mean-new_mean)/new_std)**2)
    return term1+term2

In [86]:
kl(1,2,0.3,0.4)

-3.1939320724517812